################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/cmu.c \
../src/events.c \
../src/gpio.c \
../src/i2c.c \
../src/letimer.c \
../src/power_level.c \
../src/sleep_mode.c 

OBJS += \
./src/cmu.o \
./src/events.o \
./src/gpio.o \
./src/i2c.o \
./src/letimer.o \
./src/power_level.o \
./src/sleep_mode.o 

C_DEPS += \
./src/cmu.d \
./src/events.d \
./src/gpio.d \
./src/i2c.d \
./src/letimer.d \
./src/power_level.d \
./src/sleep_mode.d 


# Each subdirectory must supply rules for building sources it contributes
src/cmu.o: ../src/cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/cmu.d" -MT"src/cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/events.o: ../src/events.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/events.d" -MT"src/events.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/gpio.o: ../src/gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/gpio.d" -MT"src/gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/i2c.o: ../src/i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/i2c.d" -MT"src/i2c.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/letimer.o: ../src/letimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/letimer.d" -MT"src/letimer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/power_level.o: ../src/power_level.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/power_level.d" -MT"src/power_level.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/sleep_mode.o: ../src/sleep_mode.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-DHAL_CONFIG=1' '-D__HEAP_SIZE=0xD00' '-D__STACK_SIZE=0x800' '-DEFR32BG13P632F512GM48=1' -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/soc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/halconfig/inc/hal-config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/protocol/bluetooth/ble_stack/inc/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/drivers" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emlib/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/CMSIS/Include" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/app/bluetooth/common/stack_bridge" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/halconfig" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/common/bsp" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/common" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/Device/SiliconLabs/EFR32BG13P/Source/GCC" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/src" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/tempdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/sleep/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/uartdrv/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/hardware/kit/EFR32BG13_BRD4104A/config" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/gpiointerrupt/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/emdrv/common/inc" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/radio/rail_lib/chip/efr32" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader/api" -I"/home/mortzula/Workspace/ecen_5823/soc-empty" -I"/home/mortzula/Workspace/ecen_5823/soc-empty/platform/bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"src/sleep_mode.d" -MT"src/sleep_mode.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


